// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify.
// It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id: 'us-east-1:6e835af1-85ad-4eb7-81d0-73a993b0a9c7',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_GwFU3AwTi',
  aws_user_pools_web_client_id: '24a7fp9j21guh62f67j6oars0p',
  oauth: {},
  aws_user_files_s3_bucket: 'media-projecte3577ba9ab8c460ebc91cb311da648f6dev-dev',
  aws_user_files_s3_bucket_region: 'us-east-1',
  aws_user_files_s3_dangerously_connect_to_http_endpoint_for_testing: true,
  aws_content_delivery_bucket: 'media-project-20191226180449-hostingbucket-dev',
  aws_content_delivery_bucket_region: 'us-east-1',
  aws_content_delivery_url: 'http://media-project-20191226180449-hostingbucket-dev.s3-website-us-east-1.amazonaws.com',
};


export default awsmobile;
